title: 'Government Technology Agency'
description: 'Empowering our nation through technology. From transforming the delivery of Government Digital Services to building Smart Nation Infrastructure,  GovTech uses technology to improve the lives of everyone in Singapore.'
url: 'https://www.tech.gov.sg'
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
collections:
    careers:
        output: true
    who-we-are:
        output: true
    products-and-services:
        output: true
resources_name: media
paginate: 12
paginate_path: '/media/page:num'
custom_css_path: /do-not-touch/theme-colors/custom.css
custom_print_css_path: /assets/css/print.css
google-tag-manager: GTM-KJNR9MC
recommender: true
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
include:
    - _redirects
favicon: /images/favicon-govtech.ico
google-analytics: UA-82296306-1
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
