[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' https://assets.dcube.cloud https://assets.wogaa.sg https://assets.adobedtm.com https://www.google-analytics.com https://cdnjs.cloudflare.com https://va.ecitizen.gov.sg https://*.cloudfront.net https://printjs-4de6.kxcdn.com https://unpkg.com 'unsafe-eval'; object-src 'none'; style-src 'self' https://fonts.googleapis.com/ https://*.cloudfront.net https://va.ecitizen.gov.sg https://assets.wogaa.sg https://cdnjs.cloudflare.com 'unsafe-inline'; img-src *; media-src *; frame-src https://wogaa.demdex.net/ https://www.youtube.com; font-src * data:; connect-src https://dpm.demdex.net https://www.google-analytics.com https://stats.g.doubleclick.net https://api.sentiments.wogaa.sg https://va.ecitizen.gov.sg; report-uri https://www.infocommsociety.com/~yicheng/csp-report/"
